pizza_api_key : <key>
noip_domain: <domain>
noip_username: <username>
noip_password: <password>

sites:
  photos:
    local_host : photos
    local_port : 80
    redirect_domain : photos.<domain>.duckdns.org
  nextcloud:
    local_host : nextcloud
    local_port : 80
    redirect_domain : nextcloud.<domain>.duckdns.org
